### ISSUE TITLE
Cross-Channel Broadcasting

### ISSUE THREAD

**Issue by TlengSHU** [dannuic/MQ2Dan#19]
The channel broadcast is a brilliant idea of DanNet per se, but it seems you just can not do cross-channel broadcasting.

For example, your tank, which you will play foreground, hit /dge priest /sit.

It won't actually work unless you /djoin priest on your tank first.

But then /djoin generates another problem if you have MORE THAN ONE TANK joined the priest channel, like one of your tank fires /dge priest /follow

all your priests and all your OTHER tanks will do follow which is not your initial intention to ONLY move the priests.

So that loses the majority of the advantage of designing those channels.

Is it possible to make a cross-channel broadcasting function please？ 

P.S. I knew we can achieve what i was saying by using this

/dge /if ($\{Select[${Me.Class.ShortName},ENC,WIZ,MAG,NEC]}) /mqp on

That will put all caster pause the macro without joining any channel, but still, that's a long ass command which can be simplfied if we got the cross-channel broadcasting.

**Comment by dannuic** [comment]
Fixed in 0.7502
